include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - camel_case_types
    - library_names
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_empty_else
    - unnecessary_brace_in_string_interps
    - avoid_redundant_argument_values
    - leading_newlines_in_multiline_strings
    - curly_braces_in_flow_control_structures
    - slash_for_doc_comments
    - avoid_relative_lib_imports
    - constant_identifier_names
    - lines_longer_than_80_chars
    - implementation_imports
    - prefer_relative_imports
    - avoid_init_to_null
    - prefer_adjacent_string_concatenation
    - prefer_interpolation_to_compose_strings
    - prefer_collection_literals
    - avoid_function_literals_in_foreach_calls
    - prefer_iterable_whereType
