include: package:flutter_lints/flutter.yaml
linter:
  rules:
    unnecessary_const: false
    prefer_const_constructors: false
    avoid_print: false
    prefer_const_declarations: false
    prefer_const_constructors_in_immutables: false
