name: pocket_tomyo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  collection: ^1.16.0
  get_it: ^7.2.0

  spine_flutter:
    git: https://github.com/khulegu/spine-flutter-custom.git

  firebase_core: ^1.19.1
  cloud_firestore: ^3.2.1
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: 4.0.6
  flutter_svg: ^1.1.0
  cached_network_image: 3.2.1
  path_provider: ^2.0.11
  carousel_slider: 4.1.1
  flutter_secure_storage: 5.0.2
  figma_squircle: ^0.5.3
  
  pinput: 2.2.11
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.7.0
  

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  assets:
    - assets/locales/
    - assets/svgs/
    - assets/images/
    - assets/svgs/nav/
    - assets/svgs/profile/
    - assets/images/tiny/
    - assets/images/tiny/hat/
    - assets/svgs/tiny/

    - assets/
    - assets/characters/
    - assets/png/
    - assets/spine/player/
    - assets/spine/boss/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/static/Inter-Regular.ttf
        - asset: fonts/Inter/static/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter/static/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter/static/Inter-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins/Poppins-Black.ttf
          weight: 900

  uses-material-design: true
