name: pocket_tomyo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: 4.0.6
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  cached_network_image: 3.2.1
  sqflite: ^2.0.2+1
  path_provider: ^2.0.11
  carousel_slider: 4.1.1
  flutter_secure_storage: 5.0.2
  figma_squircle: ^0.5.3
  hive: 2.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/locales/
    - assets/svgs/
    - assets/images/
    - assets/svgs/nav/
    - assets/svgs/profile/
  uses-material-design: true
